// <auto-generated />
namespace STAR.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addinglogintable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinglogintable));
        
        string IMigrationMetadata.Id
        {
            get { return "201608241420199_adding login table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
