// <auto-generated />
namespace STAR.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addlogintableagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlogintableagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201608241527009_add login table again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
